### ISSUE TITLE
Falha ao pegar as variáveis 

### ISSUE THREAD

**Issue by yuriprawucki1** [Martlark/pg_dump#10]
Olá, estou testando essa imagem no meu ambiente porém percebi que o Dump não é realizado pois o Shell Script não consegue ler as variáveis declaradas como POSTGRES_DB, PGPORT…

Fiz um teste exportando a variável “export $PGPORT=5432”. Com isso funciona.

**Comment by Martlark** [comment]
"Hello, I'm testing this image in my environment but I noticed that the Dump is not performed because the Shell Script cannot read the variables declared as POSTGRES_DB, PGPORT...

I did a test by exporting the variable “export $PGPORT=5432”. With that it works."
